aliases:
  - &install-pip |
    apt-get update
    apt-get install python3-pip -y

  - &install-dependencies |
    pip install -q --user flake8 pylint pytest six

  - &setup-environment |
    echo 'export PATH="$PATH:$HOME/.local/bin"' >> $BASH_ENV

  - &run-tests |
    flake8 tests src setup.py
    pylint -E src/richenum
    pylint -E setup.py

version: 2
jobs:
  test-3.5: &test-template
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: setup environment
          command: *setup-environment
      - run:
          name: install dependencies
          command: *install-dependencies
      - run:
          name: run tests
          command: *run-tests
  test-3.6:
    <<: *test-template
    docker:
    - image: circleci/python:3.6
  test-3.7:
    <<: *test-template
    docker:
    - image: circleci/python:3.7
  test-3.8:
    <<: *test-template
    docker:
    - image: circleci/python:3.8

workflows:
  version: 2
  test:
    jobs:
      - test-3.5
      - test-3.6
      - test-3.7
      - test-3.8